/**
 * @fileoverview Server-side Cloudflare Images I/O via the `IMAGES` binding
 * (token-free). Two jobs:
 *   - fetch-for-provider: pull an image's ORIGINAL bytes to hand to a model.
 *     Uses `env.IMAGES.hosted.image(id).bytes()` — a deliberate improvement over
 *     the spec's "fetch the full variant" (no public URL, no signed-URL concern).
 *   - upload-back: write a provider's generated bytes back to Images.
 *
 * Proxying bytes through the Worker is fine HERE (server-side, output already in
 * hand) — the no-proxy rule is specifically about BROWSER uploads (see
 * direct-upload.ts).
 */

import { NotFoundError } from "../errors";

/** Fetch an image's original bytes from Cloudflare Images. */
export async function fetchImageBytes(env: Env, cfImageId: string): Promise<ArrayBuffer> {
  const stream = await env.IMAGES.hosted.image(cfImageId).bytes();
  if (!stream) throw new NotFoundError(`Cloudflare Images object ${cfImageId} not found.`);
  return new Response(stream).arrayBuffer();
}

/** Fetch original bytes and base64-encode them for a provider request body. */
export async function fetchImageBase64(env: Env, cfImageId: string): Promise<string> {
  return arrayBufferToBase64(await fetchImageBytes(env, cfImageId));
}

export interface UploadResult {
  cfImageId: string;
  filename: string | null;
}

/**
 * Upload bytes to Cloudflare Images (e.g. a provider's output, or a rasterised
 * mask PNG). Returns the new image id.
 */
export async function uploadImageBytes(
  env: Env,
  bytes: ArrayBuffer | ReadableStream<Uint8Array>,
  opts: { filename?: string; metadata?: Record<string, unknown> } = {},
): Promise<UploadResult> {
  // Structural cast: the `IMAGES` binding's return type is shadowed by the
  // still-installed @cloudflare/workers-types (whose ImageMetadata differs from
  // the generated runtime one). We only need id + filename.
  const meta = (await env.IMAGES.hosted.upload(bytes, {
    filename: opts.filename,
    metadata: opts.metadata,
  })) as unknown as { id: string; filename?: string };
  return { cfImageId: meta.id, filename: meta.filename ?? null };
}

/**
 * Chunked base64 encoder — avoids `String.fromCharCode(...hugeArray)` blowing the
 * call-stack argument limit on multi-MB images.
 */
export function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  const CHUNK = 0x8000;
  let binary = "";
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(binary);
}
