/**
 * @fileoverview The declarative model catalog — pinned model ids, one entry per
 * selectable model. NO dynamic "latest" resolution. Adding a model = adding an
 * entry here + updating `task_model_defaults` in D1. Imagen is intentionally
 * absent (deprecated, shuts down 2026-08-17).
 *
 * QUARTERLY REVIEW: re-check every pinned id + `deprecated` flag against provider
 * docs each quarter.
 *
 * MASK FINDING (from the Gemini image API contract): Gemini image models have NO
 * mask-channel parameter — inpainting is SEMANTIC (prompt phrasing / compositing).
 * So all Gemini image models are `mask_inpainting: false` + `mask_emulated_only:
 * true`; a masked edit on them is emulated and the revision is flagged
 * `mask_emulated`. OpenAI's image model does have a native mask channel.
 */

import type { ModelEntry } from "./types";

const GEMINI_ASPECTS = ["1:1", "3:4", "4:3", "9:16", "16:9"];

export const MODEL_CATALOG: ModelEntry[] = [
  {
    id: "gemini-3.1-flash-image",
    provider: "google",
    display_name: "Gemini 3.1 Flash Image",
    default_for: ["image_generate", "image_edit"],
    notes: "Generalist workhorse. Search + Image Search grounding, up to 14 reference images, controllable thinking. Only model with Image Search grounding + video input. Masking is emulated (no mask channel).",
    capabilities: {
      text_to_image: true,
      image_to_image: true,
      mask_inpainting: false,
      mask_emulated_only: true,
      multi_reference_image: true,
      blueprint_json: true,
      grounding_web: true,
      grounding_image_search: true,
      thinking_controllable: true,
      interleaved_output: false,
      video_generation: false,
      segmentation: false,
      max_reference_images: 14,
      max_resolution: "4K",
      supported_aspect_ratios: GEMINI_ASPECTS,
      cost_per_image: null,
    },
  },
  {
    id: "gemini-3-pro-image",
    provider: "google",
    display_name: "Gemini 3 Pro Image",
    notes: "Premium: complex work, best text rendering, interleaved text+image output. Thinking always on. Masking is emulated.",
    capabilities: {
      text_to_image: true,
      image_to_image: true,
      mask_inpainting: false,
      mask_emulated_only: true,
      multi_reference_image: true,
      blueprint_json: true,
      grounding_web: true,
      grounding_image_search: false,
      thinking_controllable: false,
      interleaved_output: true,
      video_generation: false,
      segmentation: false,
      max_reference_images: 14,
      max_resolution: "4K",
      supported_aspect_ratios: GEMINI_ASPECTS,
      cost_per_image: null,
    },
  },
  {
    id: "gemini-3.1-flash-lite-image",
    provider: "google",
    display_name: "Gemini 3.1 Flash Lite Image",
    notes: "Cheapest. 1K only. No grounding, no multi-reference, no multi-turn. Masking emulated.",
    capabilities: {
      text_to_image: true,
      image_to_image: true,
      mask_inpainting: false,
      mask_emulated_only: true,
      multi_reference_image: false,
      blueprint_json: false,
      grounding_web: false,
      grounding_image_search: false,
      thinking_controllable: false,
      interleaved_output: false,
      video_generation: false,
      segmentation: false,
      max_reference_images: 0,
      max_resolution: "1K",
      supported_aspect_ratios: GEMINI_ASPECTS,
      cost_per_image: null,
    },
  },
  {
    id: "gemini-2.5-flash-image",
    provider: "google",
    display_name: "Gemini 2.5 Flash Image (legacy)",
    deprecated: true,
    notes: "Legacy — docs recommend migrating off. Registered, never defaulted.",
    capabilities: {
      text_to_image: true,
      image_to_image: true,
      mask_inpainting: false,
      mask_emulated_only: true,
      multi_reference_image: true,
      blueprint_json: false,
      grounding_web: false,
      grounding_image_search: false,
      thinking_controllable: false,
      interleaved_output: false,
      video_generation: false,
      segmentation: false,
      max_reference_images: 3,
      max_resolution: "1K",
      supported_aspect_ratios: GEMINI_ASPECTS,
      cost_per_image: null,
    },
  },
  {
    id: "gemini-omni-flash-preview",
    provider: "google",
    display_name: "Gemini Omni Flash (video, preview)",
    default_for: ["video"],
    notes: "Preview. Text-to-video + image-to-video. Multi-turn via previous_interaction_id. 16:9 / 9:16 only.",
    capabilities: {
      text_to_image: false,
      image_to_image: false,
      mask_inpainting: false,
      mask_emulated_only: false,
      multi_reference_image: true,
      blueprint_json: false,
      grounding_web: false,
      grounding_image_search: false,
      thinking_controllable: false,
      interleaved_output: false,
      video_generation: true,
      segmentation: false,
      max_reference_images: 3,
      max_resolution: "1K",
      supported_aspect_ratios: ["16:9", "9:16"],
      cost_per_image: null,
    },
  },
  {
    id: "gemini-3.6-flash",
    provider: "google",
    display_name: "Gemini 3.6 Flash (understanding)",
    default_for: ["understand", "segment", "decompose"],
    notes: "Captioning, detection, segmentation (box_2d + mask polygon normalised 0–1000). Use thinking_level=minimal for segmentation.",
    capabilities: {
      text_to_image: false,
      image_to_image: false,
      mask_inpainting: false,
      mask_emulated_only: false,
      multi_reference_image: false,
      blueprint_json: true,
      grounding_web: false,
      grounding_image_search: false,
      thinking_controllable: true,
      interleaved_output: false,
      video_generation: false,
      segmentation: true,
      max_reference_images: 0,
      max_resolution: "1K",
      supported_aspect_ratios: GEMINI_ASPECTS,
      cost_per_image: null,
    },
  },
  {
    id: "gpt-image-1",
    provider: "openai",
    display_name: "OpenAI gpt-image-1 (fallback)",
    notes: "OpenAI image model — has a native mask channel. VERIFY the current id against OpenAI docs before relying on it.",
    capabilities: {
      text_to_image: true,
      image_to_image: true,
      mask_inpainting: true,
      mask_emulated_only: false,
      multi_reference_image: false,
      blueprint_json: false,
      grounding_web: false,
      grounding_image_search: false,
      thinking_controllable: false,
      interleaved_output: false,
      video_generation: false,
      segmentation: false,
      max_reference_images: 0,
      max_resolution: "2K",
      supported_aspect_ratios: ["1:1", "3:2", "2:3"],
      cost_per_image: null,
    },
  },
];
